### ISSUE TITLE
旋律概形に沿った音を鳴らす

### ISSUE THREAD

**Issue by KazukiOtomo** [ItisNoMatter/melodious_pazzle#17]

**Comment by yud0uhu** [comment]
実装イメージ
![旋律概形 1](https://user-images.githubusercontent.com/60646787/130244970-9fc601ed-ac3a-4f9c-9b2a-518aca462b12.png)
・自機からオブジェクトがどんどん生成される
・生成されたオブジェクトは左に流れる
・自機が高さを変えることで生成されたオブジェクトたちがまるで波のように見える（旋律概形の表現）
・流れていったオブジェクトが画面左端のブロックに当たると高さに対応した音が出る

**Comment by KazukiOtomo** [comment]
対象物を生成する
https://your-3d.com/unity-instantiate-obj/

**Comment by KazukiOtomo** [comment]
・左の音のノーツ(?)を受け取る四角形は位置座標を固定しました。
・現在、自機からノーツを出す機能を実装中ですが、
　　　→・ノーツ同士の重なりをどのように実現するか
　　　　・スクリプトの実行タイミングが指定できない(コルーチン使ってるのに...)
という問題に直面しています。。。
