### ISSUE TITLE
クリアイメージの作成

### ISSUE THREAD

**Issue by yud0uhu** [ItisNoMatter/melodious_pazzle#25]
- クリア条件を確立させる

**Comment by KazukiOtomo** [comment]
・取得アイテム（ラーメンの具）のコンプリートをもってクリアとする（仮）

**Comment by yud0uhu** [comment]
https://jamboard.google.com/d/1byrQkBQhAKoAE5LV2qYxdFnAB1TeWEDosy931087Hb0/viewer?f=0
